### ISSUE TITLE
Failing to import NSX RAML file 

### ISSUE THREAD

**Issue by lrevnic** [SmartBear/soapui-raml-plugin#15]
RAML parser fails to parse NSX RAML file. Seems to be related to displayName and baseUri.
NSX RAML location: https://github.com/vmware/nsxraml 

Error: 
2015-10-19 12:30:31,693 ERROR [errorlog] java.lang.RuntimeException: Builder not found for ; valueNode=>
java.lang.RuntimeException: Builder not found for ; valueNode=>
at org.raml.parser.builder.DefaultTupleBuilder.getBuilderForTuple(DefaultTupleBuilder.java:68)
at org.raml.parser.visitor.YamlDocumentBuilder.onTupleStart(YamlDocumentBuilder.java:264)
at org.raml.parser.visitor.NodeVisitor.doVisitMappingNode(NodeVisitor.java:145)

**Comment by avoltmer** [comment]
More information on what works and what does not work. Note that I can't remove the displayName as other clients of the NSX RAML consume this information. 

The following fails to import:

#%RAML 0.8
title: VMware NSX for vSphere
baseUri: https://{nsxmanager}/api
baseUriParameters:
  nsxmanager:
    displayName: nsxManager
    description: This is the hostname or IP of NSX Manager
version: 6.2.2
securedBy: [basic]
securitySchemes:
  - basic:
      type: Basic Authentication
/2.0/vdn/scopes/{scopeId}/virtualwires:
  displayName: logicalSwitches
  description: Create and List operations of logical switches inside a Transport Zone (scope)
  uriParameters:
      scopeId:
        required: true
        displayName: scopeId
        description: A valid scope Id
  get:
    displayName: logicalSwitchList
    description: Lists all logical Switches in the Transport Zone (Scope)
  post:
    displayName: logicalSwitchCreate
    description: creates a logicalSwitch
    body:
      application/xml:
        example: |
          <virtualWireCreateSpec>
            <name>ls-1</name>
            <description>Example Logical Switch</description>
            <tenantId></tenantId>
            <controlPlaneMode>UNICAST</controlPlaneMode>
          </virtualWireCreateSpec>
        schema: |
          <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:element name="virtualWireCreateSpec">
              <xs:complexType>
                <xs:sequence>
                  <xs:element type="xs:string" name="name"/>
                  <xs:element type="xs:string" name="description"/>
                  <xs:element type="xs:string" name="tenantId"/>
                  <xs:element type="xs:string" name="controlPlaneMode"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:schema>

This example works:

#%RAML 0.8
title: VMware NSX for vSphere
baseUri: https://nsxmgr-l-01a.corp.local/api
version: 6.2.2
securedBy: [basic]
securitySchemes:
  - basic:
      type: Basic Authentication
/2.0/vdn/scopes/{scopeId}/virtualwires:
  displayName: logicalSwitches
  description: Create and List operations of logical switches inside a Transport Zone (scope)
  uriParameters:
      scopeId:
        required: true
        displayName: scopeId
        description: A valid scope Id
  get:
    description: Lists all logical Switches in the Transport Zone (Scope)
  post:
    description: creates a logicalSwitch
    body:
      application/xml:
        example: |
          <virtualWireCreateSpec>
            <name>ls-1</name>
            <description>Example Logical Switch</description>
            <tenantId></tenantId>
            <controlPlaneMode>UNICAST</controlPlaneMode>
          </virtualWireCreateSpec>
        schema: |
          <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:element name="virtualWireCreateSpec">
              <xs:complexType>
                <xs:sequence>
                  <xs:element type="xs:string" name="name"/>
                  <xs:element type="xs:string" name="description"/>
                  <xs:element type="xs:string" name="tenantId"/>
                  <xs:element type="xs:string" name="controlPlaneMode"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:schema>

**Comment by lrevnic** [comment]
It seems that the displayName issue on methods was also an issue in the raml-java-parser.
The issue #67 (https://github.com/raml-org/raml-java-parser/issues/67) seems to be fixed since July, 2015 and included in raml-java-parser 0.9-SNAPSHOT that is delivered with soapui-raml-plugin-0.4
